import { Nav } from '@/components'
import './globals.css'
import Providers from './providers'

export const metadata = {
  title: 'Countries API',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  )
}
