import { Nav } from '@/components'
import './globals.css'

export const metadata = {
  title: 'Countries API',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='px-4 md:px-10 lg:px-16 py-5 ' >
        <Nav />
        {children}
      </body>
    </html>
  )
}
